### ISSUE TITLE
PERF : MDEIM for nonlinear term is sooooo slow

### ISSUE THREAD

**Issue by KikeM** [KikeM/romtime#38]
I wonder what is going on there ...

It's true that there are three nested loops:
- Parameter space
  - Timestemps
    - Basis vectors

Perhaps I could combine the latter two and use `multiprocessing`.   

---

That being said, it has more or less acceptable times (30 mins por 10 parameters for each ROM/DEIM/MDEIM) to get some results and pour them in a document.

**Comment by emvalbuena** [comment]
It was slow because the basis was orthogonal and the trilinear form well ... linear haha.

Hence the SVD could not compress.
